package storageapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author juan_
 */
public class StorageInterface extends javax.swing.JFrame {

    
    
    /**
     * Creates new form StorageInterface
     */
    public StorageInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registerbtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        productIdLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        purchaseLabel = new javax.swing.JLabel();
        saleLabel = new javax.swing.JLabel();
        suplierIdLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        prodcutIdTextField = new javax.swing.JTextField();
        quantityTextField = new javax.swing.JTextField();
        categoryTexxtField = new javax.swing.JTextField();
        purchaseTextField = new javax.swing.JTextField();
        suplierIdTextField = new javax.swing.JTextField();
        saleTextField = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerbtn.setText("Register");
        registerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbtnMouseClicked(evt);
            }
        });
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });

        nameLabel.setText("Product Name:");

        productIdLabel.setText("Product ID:");

        categoryLabel.setText("Category:");

        quantityLabel.setText("Quantity:");

        purchaseLabel.setText("Purchase Price:");

        saleLabel.setText("Sale Price:");

        suplierIdLabel.setText("Suplier ID:");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        quantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTextFieldActionPerformed(evt);
            }
        });

        saleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleTextFieldActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBtnMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setLineWrap(true);
        jTextArea1.setEditable(false);
        jScrollPane1.setViewportView(jTextArea1);


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(registerbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchBtn)
                .addGap(57, 57, 57)
                .addComponent(deleteBtn)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearBtn)
                .addGap(263, 263, 263))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(categoryLabel)
                        .addGap(295, 295, 295)
                        .addComponent(suplierIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(purchaseLabel))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(categoryTexxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(nameTextField))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(suplierIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prodcutIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(purchaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(saleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productIdLabel)
                    .addComponent(prodcutIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(categoryTexxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suplierIdLabel)
                    .addComponent(suplierIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchaseLabel)
                    .addComponent(purchaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saleLabel)
                    .addComponent(saleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityLabel)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(clearBtn)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerbtn)
                    .addComponent(editBtn)
                    .addComponent(searchBtn)
                    .addComponent(deleteBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents




    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtnActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void saleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saleTextFieldActionPerformed

    private void quantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTextFieldActionPerformed

    private void registerbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbtnMouseClicked
        // TODO add your handling code here:
        insertarProducto(Integer.valueOf(prodcutIdTextField.getText()),nameTextField.getText(),categoryTexxtField.getText(),Integer.valueOf(quantityTextField.getText()),Double.valueOf(purchaseTextField.getText()),Double.valueOf(saleTextField.getText()),Integer.valueOf(suplierIdTextField.getText()));
        

    }//GEN-LAST:event_registerbtnMouseClicked

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        // TODO add your handling code here:
        actualizarProducto(Integer.valueOf(prodcutIdTextField.getText()),nameTextField.getText(),categoryTexxtField.getText(),Integer.valueOf(quantityTextField.getText()),Double.valueOf(purchaseTextField.getText()),Double.valueOf(saleTextField.getText()),Integer.valueOf(suplierIdTextField.getText()));

    }//GEN-LAST:event_editBtnMouseClicked

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        // TODO add your handling code here:

        buscarProducto("Nombre",nameTextField.getText());

    }//GEN-LAST:event_searchBtnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
        eliminarProducto(Integer.valueOf(prodcutIdTextField.getText()));
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void clearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseClicked
        // TODO add your handling code here:
        nameTextField.setText("");
        prodcutIdTextField.setText("");
        quantityTextField.setText("");
        categoryTexxtField.setText("");
        purchaseTextField.setText("");
        suplierIdTextField.setText("");
        saleTextField.setText("");
        jTextArea1.setText("");


    }//GEN-LAST:event_clearBtnMouseClicked

    //Metodo buscar producto
    public void buscarProducto(String criterio, String valor) {
    String query = "SELECT * FROM Producto WHERE " + criterio + " LIKE ?"; //SQL query
    try (Connection con = DBConnection.conectar();
         PreparedStatement pst = con.prepareStatement(query)) {

        pst.setString(1, "%" + valor + "%");

        ResultSet rs = pst.executeQuery();
        StringBuilder sb = new StringBuilder();
        if (!rs.isBeforeFirst()) { // No hay registros
            sb.append("Product not found");
        } else {
            while (rs.next()) {

                sb.append("Code: ").append(rs.getInt("CodigoProducto")).append("\n")
                .append("Name: ").append(rs.getString("Nombre")).append("\n")
                .append("Category: ").append(rs.getString("Categoria")).append("\n")
                .append("Quantity: ").append(rs.getInt("Cantidad")).append("\n")
                .append("Purchase price: ").append(rs.getDouble("PrecioCompra")).append("\n")
                .append("Sale price: ").append(rs.getDouble("PrecioVenta")).append("\n")
                .append("Suplier ID: ").append(rs.getInt("ProveedorID")).append("\n")
                .append("-------------------------\n");
            }
        }
        jTextArea1.setText(sb.toString());
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

//Metodo para insertar un producto
    public void insertarProducto(int codigoProducto, String nombre, String categoria, int cantidad, double precioCompra, double precioVenta, int proveedorID) {
        String query = "INSERT INTO Producto (CodigoProducto, Nombre, Categoria, Cantidad, PrecioCompra, PrecioVenta, ProveedorID) VALUES (?, ?, ?, ?, ?, ?, ?)";
        try (Connection con = DBConnection.conectar();
             PreparedStatement pst = con.prepareStatement(query)) {

            pst.setInt(1, codigoProducto);
            pst.setString(2, nombre);
            pst.setString(3, categoria);
            pst.setInt(4, cantidad);
            pst.setDouble(5, precioCompra);
            pst.setDouble(6, precioVenta);
            pst.setInt(7, proveedorID);

            int rowsInserted = pst.executeUpdate();
            if (rowsInserted > 0) {
                jTextArea1.setText("Product inserted successfully.");
                System.out.println("Producto insertado correctamente.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


//Metodo para actualizar un producto
public void actualizarProducto(int codigoProducto, String nombre, String categoria, int cantidad, double precioCompra, double precioVenta, int proveedorID) {
    String query = "UPDATE Producto SET Nombre = ?, Categoria = ?, Cantidad = ?, PrecioCompra = ?, PrecioVenta = ?, ProveedorID = ? WHERE CodigoProducto = ?";
    try (Connection con = DBConnection.conectar();
         PreparedStatement pst = con.prepareStatement(query)) {

        pst.setString(1, nombre);
        pst.setString(2, categoria);
        pst.setInt(3, cantidad);
        pst.setDouble(4, precioCompra);
        pst.setDouble(5, precioVenta);
        pst.setInt(6, proveedorID);
        pst.setInt(7, codigoProducto);

        int rowsUpdated = pst.executeUpdate();
        if (rowsUpdated > 0) {
            jTextArea1.setText("Product update succesfully");
            System.out.println("Producto actualizado correctamente.");
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

//Metodo para eliminar un producto
public void eliminarProducto(int codigoProducto) {
    String query = "DELETE FROM Producto WHERE CodigoProducto = ?";
    try (Connection con = DBConnection.conectar();
         PreparedStatement pst = con.prepareStatement(query)) {

        pst.setInt(1, codigoProducto);

        int rowsDeleted = pst.executeUpdate();
        if (rowsDeleted > 0) {
            jTextArea1.setText("Product delete succesfully.");
            System.out.println("Producto eliminado correctamente.");
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
























    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StorageInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StorageInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StorageInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StorageInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StorageInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField categoryTexxtField;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField prodcutIdTextField;
    private javax.swing.JLabel productIdLabel;
    private javax.swing.JLabel purchaseLabel;
    private javax.swing.JTextField purchaseTextField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JButton registerbtn;
    private javax.swing.JLabel saleLabel;
    private javax.swing.JTextField saleTextField;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel suplierIdLabel;
    private javax.swing.JTextField suplierIdTextField;
    // End of variables declaration//GEN-END:variables
}
